<?php
    define("FV_APP_ROOT", fvSite::$fvConfig->get("path.application." . FV_APP . ".root"));
    define("FV_APP_WEB_ROOT", fvSite::$fvConfig->get("path.application." . FV_APP . ".web_root"));
?>

layoult: FlatLayoult

dir_web_root: %FV_APP_WEB_ROOT%

access:
  enable: true
  user_class: User
  deny_page: %dir_web_root%login/deny/
  login_page: /login/
  do_login: /login/login/
  login_module: login
  autologin: true
  cookie_name: user_id
  lifetime: +1 day
  do_logout: /login/logout/
  login_acl: acl_backend_login
  login_interval: 60
  
page_404: %dir_web_root%404.php
error_page: %dir_web_root%404.php

title: Администрирование fv

filters: [fvSecurityFilter, fvFilterFilter, fvActionFilter]

pager:
  show_per_page: 100

path:
  modules: %FV_APP_ROOT%modules/
  images: %dir_web_root%img/
  upload:
    tmp_dir: %tech_web_root%img/upload/tmp/
    web_tmp_dir: /img/upload/tmp/
    web_root_dir: /img/upload/
    root_dir: %tech_web_root%img/upload/
  smarty:
    template: %FV_APP_ROOT%template/
    compile: %path.smarty.template%template_c/
    blocks: %path.smarty.template%blocks/ 
    
upload:
  allowed_filesize: 4000000
  
  allowed_ext: [jpg, jpeg, png, xls, xlsx, doc, docx]

includes:
  css: [%path.css%backend.css,%path.css%main_menu.css,%path.css%jquery-ui/style.css]
  js: [%path.js%jquery.min.js, %path.js%history/unFocus-History-p.js, %path.js%prototype/prototype.js, %path.js%backend/menu.js,  %path.js%prototype/scriptaculous.js, %path.js%popupmenu.js, %path.js%center_window.js, %path.js%backend/common.js, %path.js%jquery-ui.js, %path.js%uploader/swfobject.js, %path.js%uploader/jquery.uploadify.js, %path.js%common.js]    
