<?php
    define("FV_APP_ROOT", fvSite::$fvConfig->get("path.application." . FV_APP . ".root"));
    define("FV_APP_WEB_ROOT", fvSite::$fvConfig->get("path.application." . FV_APP . ".web_root"));
?>

layoult: ModuleLayoult

dir_web_root: %FV_APP_WEB_ROOT%
dir_root: %FV_APP_ROOT%

access:
  enable: false
  user_class: User
  deny_page: %dir_web_root%login/deny/
  login_page: /login
  login_module: login
  autologin: false
  cookie_name: user_id
  lifetime: +1 day
  do_logout: /login/logout/
  login_acl: acl_frontend_login

page_404: %dir_web_root%404.php
page_error: %dir_web_root%error.php

title: English 

filters: [fvSecurityFilter, fvFilterFilter, fvActionFilter]

path:
  <?php if (fvSite::$fvConfig->get("cdn_enable")): ?>
  images: %cdn_root%img/
  <?php else: ?>
  images: %dir_web_root%img/
  <?php endif; ?>
  modules: %FV_APP_ROOT%modules/
  upload:
    tmp_dir: %tech_web_root%img/upload/tmp/
    web_tmp_dir: /img/upload/tmp/
    web_root_dir: /img/upload/
    root_dir: %tech_web_root%img/upload/
  entImages: 
    Hotel: media/    
  smarty:
    template: %FV_APP_ROOT%template/
    compile: %path.smarty.template%template_c/
    blocks: %path.smarty.template%blocks/

includes:
   css: [%path.css%style.css, %path.css%jquery-ui/style.css]
   js: [%path.js%jquery-1.6.1.min.js, %path.js%common.js, %path.js%jquery-ui-1.8.16.custom.min.js]   