routes:          
  countries_list:
    url: /countries/list/:page
    module: countries
    action: list
    params:
      page: [0-9]{1,11}
      
  countries_view:
    url: /countries/view/:url
    module: countries
    action: view
    params:
      url: [a-z0-9\_]{1,255}   
      
  view-news:
    url: /news/:news_url/
    module: news
    action: view
    params:
      news_url: [a-zA-Z0-9\_]+

  tours_list:
    url: /tours/list/:tour_type_url
    module: tours
    action: list
    params:
      tour_type_url: [a-z0-9\_]{0,255}
      
      
  tours_view:
    url: /tours/view/:url
    module: tours
    action: view
    params:
      url: [a-z0-9\_]{1,255}   
      
  hotels_view:
    url: /hotels/view/:url
    module: hotels
    action: view
    params:
      url: [a-z0-9\_]{1,255}   
      
  default:
    url: /:module/:action
    params: []

    