<?php

    define("FV_ROOT", realpath(dirname(__FILE__) . "/../"));
    define("CURRENT_LANGUAGE", "ru");
    $srv = $_SERVER['SERVER_NAME'];

    if(preg_match('/http:\/\/kompas.own/',$srv))  //local version     
    {
        $__server_host = 'kompas.own';
        $__db_server_host = 'mysql.h4.newname.com.ua';
        $__db_server_user = 'newkompas';
        $__db_server_pass = 'THniXFLg';


        $__server_host = 'kompas.own';
        $__db_server_host = 'mysql.h4.newname.com.ua';
        $__db_server_user = 'newkompas';
        $__db_server_pass = 'THniXFLg';

    }
    else
    {
        $__server_host = 'kompas.own';
        $__db_server_host = 'mysql.h4.newname.com.ua';
        $__db_server_user = 'newkompas';
        $__db_server_pass = 'THniXFLg';
    }
    
    define("__SERVER_NAME", $__server_host);
    define("__DB_SERVER_NAME", $__db_server_host);
    define("__DB_SERVER_USER", $__db_server_user);
    define("__DB_SERVER_PASS", $__db_server_pass);

?>

server_name: %__SERVER_NAME%
site_name: kompas.own
dir_root: %FV_ROOT%
tech_web_root: %FV_ROOT%web/
dir_web_root: /
cdn_root: http://img.%server_name%/
cdn_enable: false
charset: utf-8
language: %CURRENT_LANGUAGE%


database:
 dsn: mysql://%__DB_SERVER_USER%:%__DB_SERVER_PASS%@%__DB_SERVER_NAME%/newkompas
 driver: mysql
 host: %__DB_SERVER_NAME%
 user: newkompas
 pass: THniXFLg
 name: newkompas
 db_prefix: newkompas.kompas_

ftp:
 server_name: %server_name%
 user: newkompas
 pass: kJEjpr3q

session:
 use_database: true
 sess_name: fv_session
 life_time: 10000
 table: %database.db_prefix%session

filters: [fvActionFilter]

path:
 font:              %tech_web_root%font/
 classes:           %dir_root%classes/
 announce_url:      http://%server_name%:2512/
 error:             %dir_root%error/error.log 
 db:                %path.framework%DB/
 entity:            %path.classes%entity/
 filters:           %path.classes%filter/
 interfaces:        %path.classes%interface/
 exceptions:        %path.classes%exceptions/
 includes:          %dir_root%includes/
 config:            %dir_root%config/
 app:               %dir_root%app/
 css:               %dir_web_root%css/
 js:                %dir_web_root%js/
 cache:             %dir_root%xcache/
 media_web:         %dir_web_root%upload/media/
 web_captcha_root:  %dir_web_root%captcha/
 tech_captcha_root: %tech_web_root%captcha/
 smarty:
  class_path: %dir_root%smarty/
 upload:
  web_temp_image:   %dir_web_root%upload/tmp/
  media:                        %tech_web_root%upload/media/
  media_web:            %dir_web_root%upload/media/
  temp_image:           %tech_web_root%upload/tmp/
  advertise:                %tech_web_root%upload/advertise/
  advertise_web:        %dir_web_root%upload/advertise/
  mediacountry:         %tech_web_root%upload/country/
  mediacountry_web: %dir_web_root%upload/country/
  icon:                         %tech_web_root%upload/icon/
  icon_web:                 %dir_web_root%upload/icon/
  mediahotel:               %tech_web_root%upload/hotel/
  mediahotel_web:       %dir_web_root%upload/hotel/
  mediatour:                %tech_web_root%upload/tour/   
  mediatour_web:        %dir_web_root%upload/tour/   
  HotOffer:                 	%tech_web_root%upload/HotOffer/   
  HotOffer_web:         	%dir_web_root%upload/HotOffer/   
  priceofday:               	%tech_web_root%upload/priceofday/   
  priceofday_web:       %dir_web_root%upload/priceofday/   
  news:                        %tech_web_root%upload/news/
  news_web:             	%dir_web_root%upload/news/
  recommend:            	%tech_web_root%upload/recommend/
  recommend_web:   	%dir_web_root%upload/recommend/ 
  mix:            	%tech_web_root%upload/mix/
  mix_web:   		%dir_web_root%upload/mix/
    
 application:
  backend:
   root: %path.app%backend/
   web_root: %dir_web_root%backend/
   config: %path.application.backend.root%config/
   classes: %path.application.backend.root%classes/
  frontend:
   root: %path.app%frontend/
   web_root: %dir_web_root%
   config: %path.application.frontend.root%config/
   classes: %path.application.frontend.root%classes/ 
     
editor:
  basepath: %dir_web_root%fckeditor/
  toolbar: fv
  config: %path.js%fvfckconfig.js
  className:
  style: width: 95%; margin: 2px 0px 10px 10px; border:solid 1px #aacfe4;

cache:
  cachetime: 60

email:
  from_name: Администратор
  from_email: alex@newname.com.ua
  administrator: newname@gmail.com
  bcc: alex@newname.com.ua
  error_email: alex@newname.com.ua
  feedback: [newname@gmail.com]
  order: [main@mytravel-ua.com,dreamka@gmail.com]
  
images:
  default_type: normal
  crbcenter:
    width: 691
    height: 254
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  crbright:
    width: 333
    height: 163
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  crbleft:
    width: 323
    height: 163
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  large:
    width: 500
    height: 500
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  normal:
    width: 300
    height: 300
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  small:
    width: 200
    height: 200
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  smalltwo:
    width: 135
    height: 100
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  smallone:
    width: 124
    height: 71
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
  thumb:
    width: 100
    height: 100
    type: <?php echo fvMediaLib::THUMB_WIDTH . "\n" ?>
pager:
  show_per_page: 8;
